baseurl = "https://maharlika.superphysics.org"
metaDataFormat = "yaml"
title = "Maharlikanism"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false

enableEmoji = true
paginate = 12

[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"


    [[languages.en.menu.main]]
        name = "/icons/megaphone.png"
        url = "advocacy"
        weight = 1

    [[languages.en.menu.main]]
        name = "/icons/help.png"
        url = "culture"
        weight = 2

    [[languages.en.menu.main]]
        name = "/icons/economic.png"
        url = "economics"
        weight = 3

    [[languages.en.menu.main]]
        name = "/icons/gavel.png"
        url = "governance"
        weight = 4

    [[languages.en.menu.main]]
        name = "/icons/book.png"
        url = "history"
        weight = 5

    [[languages.en.menu.main]]
        name = "/icons/quill.png"
        url = "laws"
        weight = 6

    [[languages.en.menu.main]]
        name = "/icons/tao.png"
        url = "metaphysics"
        weight = 7

    [[languages.en.menu.main]]
        name = "/icons/politician.png"
        url = "politicians"
        weight = 8

    [[languages.en.menu.main]]
        name = "/icons/pen.png"
        url = "writers"
        weight = 9

    [[languages.en.menu.main]]
        name = "/icons/question.png"
        url = "faq"
        weight = 10

    [[languages.en.menu.main]]
        name = "/icons/about.png"
        url = "about"
        weight = 11

    [[languages.en.menu.main]]
        name = "/icons/heart.png"
        url = "help"
        weight = 12

    [languages.en.params]
      heading = "An advocacy to change the name, culture, and socio-economics of the Philippines into Maharlika"
      intro = "Maharlika and Maharlikanism"
      sub = "Our main adocacies"
      banner = "/photos/flag.jpg"
      youtube = "PjQjps9DTXw"

    [languages.en.params.cards.a]
      icon = "/icons/sun.png"
      title = "Constitutional Virtues"
      sub = "A New, Systemic Moral Foundation"
      url = "https://superphysics.org/social/supersociology/solutions/constitutional-virtues/"
    [languages.en.params.cards.b]
      icon = "/icons/stars.png"
      title = "Federalism with Bicameral Parliament"
      sub = "Democracy with a Focus"
      url = "/governance/federalism"
    [languages.en.params.cards.c]
      icon = "/icons/help.png"
      title = "Bayanihan Economy"
      sub = "Economic Growth without Crisis"
      url = "/economics/barter"



      ## SP = Advocacy
    [languages.en.params.tricon1]
      # heading = "The Nature of the Soul"
      title = "Advocacy and History"
      # sub = "The analog universe streams in real-definition to create reality"
      #youtube = "dc4VNkfqs1s"
      #icon = "/icons/sp.png"
      #link= "/superphysics/principles"
    [languages.en.params.tricon1.items.a]
      url = "/history/meanings-maharlika"
      img= "/photos/medieval/lapu.jpg"
      title = "What is Maharlika?"
      sub = "A small country where great things come from"
    [languages.en.params.tricon1.items.b]
      url = "/advocacy/maharlikanism"
      img = "/photos/idea.jpg"
      title = "What is Maharlikanism?"
      sub = "A plan bring back the Philippines to its true state"
    [languages.en.params.tricon1.items.c]
      url = "/history/pigafetta/simplified-pigafetta"
      img = "/photos/objects/galleon.jpg"
      title = "Pigafetta's Accounts"
      sub = "What did the Spanish say about Maharlika?"
    [languages.en.params.tricon1.items.d]
      url = "https://superphysics.org/social/supersociology/solutions/constitutional-virtues/"
      img = "/photos/psych/heart.jpg"
      title = "What are Constitutional Virtues?"
      sub = "The foundations of civilization"


## mat law
    [languages.en.params.tricon2]
      # heading = "The Soul of the Physical Universe"
      title = "Politics and Law"
      sub = "Philippines versus Maharlika"
      # youtube = "3l9J6tH4iD0"
      # icon = "/icons/spmat.png"
      # link= "/material/principles"
    [languages.en.params.tricon2.items.a]
      url = "/governance/federalism"
      img= "/photos/medieval/maharlika.jpg"
      title = "Why Federalism?"
      sub = "Maharlika was a confederation of semi-independent states"
    [languages.en.params.tricon2.items.b]
      url = "/history/colonialism/"
      img= "/photos/medieval/magellan.jpg"
      title = "How Did Colonizers Get a Foothold?"
      sub = "How Divide and Conquer Works"
    [languages.en.params.tricon2.items.c]
      url= "/metaphysics/democracy-is-bad"
      img = "/photos/psych/freedom.jpg"
      title = "Why is Democracy Bad?"
      sub = "Maharlika was already Democratic"
    [languages.en.params.tricon2.items.d]
      url = "/metaphysics/marcos-aquino-rivalry"
      img = "/photos/coryv.jpg"
      title = "The Marcos-Aquino Rivalry"
      sub = "Conservative vs Liberal"


    # [languages.en.params.tricon2.items.d]
    #   url = "/material/solutions/fusion/"
    #   img= "/photos/physics/elec.jpg"
    #   title = "The Fusion Solution"
    #   sub= "We propose anti-gravity from Cartesian spacetime vortices"


# The Fourth Year of Westernized Maharlika

      ## bio econ
    [languages.en.params.tricon3]
      # heading = "The Soul of Living Entities"
      title = "Economics"
      sub = "Bayanihan as an Economic System"
      # youtube= "Y6YKmtqJak4"
      # icon = "/icons/spmed.png"
      # link= "/bio/principles"
    # [languages.en.params.tricon3.items.a]
    #   url = "/bio/principles/part-04/chapter-03/"
    #   img= "/photos/med/cancer2.jpg"
    #   title = "Cancers and Diseases Have Been Cured by Non-Western Medicine"
    #   sub = "See the wave-based alternatives to particle-based Western Medicine"
    [languages.en.params.tricon3.items.b]
      url = "/economics/maharlika-2050/"
      img= "/graphics/econ/eq.jpg"
      title = "Maharlika 2050"
      sub = "Transition to an Advanced Country"
    [languages.en.params.tricon3.items.c]
      url = "/governance/fourth-branch-government/"
      img= "/photos/balancerock.jpg"
      title = "The Fourth Branch of Government"
      sub = "The Resources Department"
    [languages.en.params.tricon3.items.d]
      url = "/metaphysics/poor-philippines/"
      img= "/photos/social/poverty.jpg"
      title = "Why the Philippines is Poor"
      sub = "How Low Morals Causes Chronic Poverty"


    [languages.en.params.tricon4]
      # heading = "The Soul of Society"
      title = "Culture and the Arts"
      sub = "Maharlikan Puso or Heart"
      # youtube = "AfByl9Mywi4"
      icon = "/icons/spsoc.png"
    [languages.en.params.tricon4.items.a]
      url = "/infrastructure/climate-change"
      img = "/photos/flood.jpg"
      title = "How Maharlika Dealt with Climate Change"
      sub = "By Prediction and Mitigation"
    [languages.en.params.tricon4.items.b]
      url = "/culture/war-adobo"
      img = "/photos/food/adobopork.jpg"
      title = "War on Adobo"
      sub = "Maharlikan Food versus Philippine Food"
    [languages.en.params.tricon4.items.c]
      url = "/culture/war-adobo/"
      img= "/photos/basket.jpg"
      title = "Bayong Ball"
      sub = "Basketball for short people"



  [languages.tl]
    contentDir = "content/tl"
    weight = 2
    languageName = "Tagalog"
    [[languages.tl.menu.main]]
        name = "/icons/question.png"
        url = "faq"
        weight = 8
    [[languages.tl.menu.main]]
        name = "/icons/about.png"
        url = "about"
        weight = 9
    [[languages.tl.menu.main]]
        name = "/icons/heart.png"
        url = "help"
        weight = 10

    [languages.tl.params]
      heading = "An advocacy to change the name, culture, and socio-economics of the Philippines into Maharlika"
      intro = "Maharlika and Maharlikanism"
      sub = "Our main adocacies"
      banner = "/photos/flag.jpg"
      youtube = "PjQjps9DTXw"

      ## SP = Advocacy
    [languages.tl.params.tricon1]
      # heading = "The Nature of the Soul"
      title = "Advocacy and History"
      # sub = "The analog universe streams in real-definition to create reality"
      #youtube = "dc4VNkfqs1s"
      #icon = "/icons/sp.png"
      #link= "/superphysics/principles"
    [languages.tl.params.tricon1.items.a]
      url = "/history/meanings-maharlika"
      img= "/photos/medieval/lapu.jpg"
      title = "What is Maharlika?"
      sub = "A small country where great things come from"
    [languages.tl.params.tricon1.items.b]
      url = "/advocacy/maharlikanism"
      img = "/photos/idea.jpg"
      title = "What is Maharlikanism?"
      sub = "A plan bring back the Philippines to its true state"
    [languages.tl.params.tricon1.items.c]
      url = "/history/pigafetta/simplified-pigafetta"
      img = "/photos/objects/galleon.jpg"
      title = "Pigafetta's Accounts"
      sub = "What did the Spanish say about Maharlika?"
    [languages.tl.params.tricon1.items.d]
      url = "https://superphysics.org/social/supersociology/solutions/constitutional-virtues/"
      img = "/photos/psych/heart.jpg"
      title = "What are Constitutional Virtues?"
      sub = "The foundations of civilization"


## mat law
    [languages.tl.params.tricon2]
      # heading = "The Soul of the Physical Universe"
      title = "Politics and Law"
      sub = "Philippines versus Maharlika"
      # youtube = "3l9J6tH4iD0"
      # icon = "/icons/spmat.png"
      # link= "/material/principles"
    [languages.tl.params.tricon2.items.a]
      url = "/governance/federalism"
      img= "/photos/medieval/maharlika.jpg"
      title = "Why Federalism?"
      sub = "Maharlika was a confederation of semi-independent states"
    [languages.tl.params.tricon2.items.b]
      url = "/history/colonialism/"
      img= "/photos/medieval/magellan.jpg"
      title = "How Did Colonizers Get a Foothold?"
      sub = "How Divide and Conquer Works"
    [languages.tl.params.tricon2.items.c]
      url= "/metaphysics/democracy-is-bad"
      img = "/photos/psych/freedom.jpg"
      title = "Why is Democracy Bad?"
      sub = "Maharlika was already Democratic"
    [languages.tl.params.tricon2.items.d]
      url = "/metaphysics/marcos-aquino-rivalry"
      img = "/photos/coryv.jpg"
      title = "The Marcos-Aquino Rivalry"
      sub = "Conservative vs Liberal"


    # [languages.tl.params.tricon2.items.d]
    #   url = "/material/solutions/fusion/"
    #   img= "/photos/physics/elec.jpg"
    #   title = "The Fusion Solution"
    #   sub= "We propose anti-gravity from Cartesian spacetime vortices"


# The Fourth Year of Westernized Maharlika

      ## bio econ
    [languages.tl.params.tricon3]
      # heading = "The Soul of Living Entities"
      title = "Economics"
      sub = "Bayanihan as an Economic System"
      # youtube= "Y6YKmtqJak4"
      # icon = "/icons/spmed.png"
      # link= "/bio/principles"
    # [languages.tl.params.tricon3.items.a]
    #   url = "/bio/principles/part-04/chapter-03/"
    #   img= "/photos/med/cancer2.jpg"
    #   title = "Cancers and Diseases Have Been Cured by Non-Western Medicine"
    #   sub = "See the wave-based alternatives to particle-based Western Medicine"
    [languages.tl.params.tricon3.items.b]
      url = "/economics/maharlika-2050/"
      img= "/graphics/econ/eq.jpg"
      title = "Maharlika 2050"
      sub = "Transition to an Advanced Country"
    [languages.tl.params.tricon3.items.c]
      url = "/governance/fourth-branch-government/"
      img= "/photos/balancerock.jpg"
      title = "The Fourth Branch of Government"
      sub = "The Resources Department"
    [languages.tl.params.tricon3.items.d]
      url = "/metaphysics/poor-philippines/"
      img= "/photos/social/poverty.jpg"
      title = "Why the Philippines is Poor"
      sub = "How Low Morals Causes Chronic Poverty"


    [languages.tl.params.tricon4]
      # heading = "The Soul of Society"
      title = "Culture and the Arts"
      sub = "Maharlikan Puso or Heart"
      # youtube = "AfByl9Mywi4"
      icon = "/icons/spsoc.png"
    [languages.tl.params.tricon4.items.b]
      url = "/infrastructure/climate-change"
      img = "/photos/flood.jpg"
      title = "How Maharlika Dealt with Climate Change"
      sub = "By Prediction and Mitigation"
    [languages.tl.params.tricon4.items.c]
      url = "/culture/war-adobo"
      img = "/photos/food/adobopork.jpg"
      title = "War on Adobo"
      sub = "Maharlikan Food versus Philippine Food"
    [languages.tl.params.tricon4.items.d]
      url = "/culture/war-adobo/"
      img= "/photos/basket.jpg"
      title = "Bayong Ball"
      sub = "Basketball for short people"



[params]
  logo = "/icons/sun.png"
  
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  # searchKeys = [
  #   "title",
  #   "link",
  #   "description"
  # ]
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright Â© 2023 | Pantrypoints Technologies"
  favicon = "/icons/sp30.png"

  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true


  hidePageThumbnail = false

# Comments system
[params.comments]
  system = "giscus"

  repo="jundalisay/superblist"
  repo-id="R_kgDOKk--Tw"
  category="General"
  category-id="DIC_kwDOKk--T84CacDf"
  mapping="pathname"
  strict="0"
  reactions-enabled="1"
  emit-metadata="0"
  input-position="bottom"
  theme="preferred_color_scheme"
  lang="en"
  crossorigin="anonymous"

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow or Support Us!"
  description = "We're building a new science and new systems for a better reality"

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/superphysicsorg"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://www.youtube.com/@superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "instagram"
  #   url = "https://instagram.com"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://www.facebook.com/superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "behance"
  #   url = "https://behance.net"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
